### ISSUE TITLE
Install Script Error

### ISSUE THREAD

**Issue by texastoastt** [Sonic-Hedgehog/Voslin-Theme#7]
The installation script seems to fail, spitting out the below error: 

Moving theme files to /var/www/paymenter/themes/voslintheme...
Running vite.js build for voslintheme...
/var/www/paymenter/node_modules/vite/dist/node/index.js:1
import { i as isInNodeModules } from './chunks/dep-b2890f90.js';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/paymenter/vite.js:1:33)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Failed to build the theme with vite.js.

**Comment by maendamedia** [comment]
Same here

**Comment by TinyBrickBoy** [comment]
same

**Comment by TinyBrickBoy** [comment]
you need to update nodejs and npm

**Comment by NirmaLKumar26** [comment]
same bro, how to fix

**Comment by TinyBrickBoy** [comment]
**FIX**
1. apt update && apt upgrade -y
2. sudo apt upgrade nodejs
3.  apt update && apt upgrade -y
4.  npm install -g npm
